window.CONTRACTORS_STUDY = {
  sources: [
    {
      id: "cslb-exam-study-guides",
      title: "CSLB Examination Study Guides",
      publisher: "California Contractors State License Board",
      url: "https://www.cslb.ca.gov/contractors/applicants/Examination_Study_Guides/",
      sourceType: "official",
      useFor: ["topic outline", "sample questions", "resource lists", "test strategy"]
    },
    {
      id: "cslb-b-general-building",
      title: "B - General Building Study Guide",
      publisher: "California Contractors State License Board",
      url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf",
      sourceType: "official",
      useFor: ["B classification topic outline", "section weights", "study references"]
    },
    {
      id: "cslb-preparing-for-exam",
      title: "Preparing for the Exam",
      publisher: "California Contractors State License Board",
      url: "https://www.cslb.ca.gov/Resources/Contractors/Journeymen/PreparingForTheExam.pdf",
      sourceType: "official",
      useFor: ["exam format", "study strategy", "test-day expectations"]
    },
    {
      id: "cslb-get-licensed",
      title: "Get Licensed to Build",
      publisher: "California Contractors State License Board",
      url: "https://www.cslb.ca.gov/Resources/GuidesAndPublications/GetLicensedToBuild_ENG0525_ADA.pdf",
      sourceType: "official",
      useFor: ["licensing process", "application education", "applicant requirements"]
    }
  ],
  exams: [
    {
      id: "general-building-b",
      title: "B - General Building",
      subtitle: "Planning, framing, core trades, finishes, and safety.",
      icon: "🏗️"
    },
    {
      id: "law-business",
      title: "Law & Business",
      subtitle: "Contracts, business practices, bonds, insurance, and compliance.",
      icon: "⚖️"
    },
    {
      id: "licensing-process",
      title: "Licensing Process",
      subtitle: "Application steps, experience, exams, bonds, insurance, and renewals.",
      icon: "📋"
    }
  ],
  questions: [
    {
      id: "ca-b-planning-001",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Planning and Estimating",
      topic: "Scope of work and code compliance",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Before pricing a room addition, what should the contractor review first?",
      choices: ["The owner's preferred paint colors", "Plans, specifications, scope of work, and applicable code requirements", "The subcontractor's marketing flyer", "Only the final inspection checklist"],
      answer: "Plans, specifications, scope of work, and applicable code requirements",
      explanation: "Planning starts by defining the work and confirming code and specification requirements before estimating labor, material, and coordination needs.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Planning and Estimating topics." },
      tags: ["planning", "estimating", "code-compliance"]
    },
    {
      id: "ca-b-planning-002",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Planning and Estimating",
      topic: "Design and construction error identification",
      difficulty: "medium",
      type: "multiple_choice",
      question: "A plan note conflicts with a detail drawing. What is the best first step before building that portion of the work?",
      choices: ["Build from memory", "Ignore the note and follow the cheapest option", "Request clarification through the proper project channel", "Let the finish subcontractor decide later"],
      answer: "Request clarification through the proper project channel",
      explanation: "The contractor should identify conflicts and coordinate clarification before work proceeds, avoiding rework and code or contract problems.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with plan/specification coordination topics." },
      tags: ["plans", "coordination"]
    },
    {
      id: "ca-b-planning-003",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Planning and Estimating",
      topic: "Cost estimation",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Which items should be included when estimating the cost of a concrete slab scope?",
      choices: ["Only the concrete delivery ticket", "Materials, labor, equipment, site conditions, and related coordination", "Only profit and overhead", "Only the square footage of the house"],
      answer: "Materials, labor, equipment, site conditions, and related coordination",
      explanation: "A complete estimate considers direct and supporting costs, not just one material quantity.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with estimating materials, equipment, and labor." },
      tags: ["estimating", "concrete"]
    },
    {
      id: "ca-b-planning-004",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Planning and Estimating",
      topic: "Field inspection performance",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Why should required inspections be scheduled before covering structural, plumbing, or electrical work?",
      choices: ["To avoid documenting the work", "Because covered work may need to be exposed again if it was not inspected", "Because inspections are optional on small jobs", "To transfer responsibility to the supplier"],
      answer: "Because covered work may need to be exposed again if it was not inspected",
      explanation: "Inspection timing is part of project coordination and helps confirm work before it is concealed.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with field inspection performance." },
      tags: ["inspection", "coordination"]
    },
    {
      id: "ca-b-planning-005",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Planning and Estimating",
      topic: "Coordination of project",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Which schedule sequence is usually most logical for a basic interior wall assembly?",
      choices: ["Paint, drywall, rough electrical, framing", "Framing, rough utilities, inspection, insulation/drywall", "Flooring, framing, inspection, rough utilities", "Cabinets, paint, rough plumbing, drywall"],
      answer: "Framing, rough utilities, inspection, insulation/drywall",
      explanation: "Project coordination depends on sequencing trades so concealed work is installed and inspected before finish layers are added.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with project coordination topics." },
      tags: ["sequence", "coordination"]
    },
    {
      id: "ca-b-framing-001",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Framing and Structural Components",
      topic: "Wall framing",
      difficulty: "easy",
      type: "multiple_choice",
      question: "What should be checked before cutting studs for a framed wall?",
      choices: ["Only the weather forecast", "Wall height, plate layout, opening locations, and plan requirements", "Only the drywall color", "The final cleaning schedule"],
      answer: "Wall height, plate layout, opening locations, and plan requirements",
      explanation: "Wall framing requires layout from plans and dimensions so openings, plates, and stud lengths fit the design.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with subfloor and wall framing." },
      tags: ["framing", "layout"]
    },
    {
      id: "ca-b-framing-002",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Framing and Structural Components",
      topic: "Roof framing",
      difficulty: "medium",
      type: "multiple_choice",
      question: "If roof framing members do not match the approved plans, what should the contractor do?",
      choices: ["Install them anyway if they look strong", "Request proper clarification or correction before continuing", "Hide the difference with roofing", "Ask the painter to note it"],
      answer: "Request proper clarification or correction before continuing",
      explanation: "Structural components should follow approved plans and specifications; conflicts require clarification before work proceeds.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with roof framing and structural components." },
      tags: ["roof", "framing", "plans"]
    },
    {
      id: "ca-b-framing-003",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Framing and Structural Components",
      topic: "Seismic hardware",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Why is seismic hardware installation especially important in California construction?",
      choices: ["It replaces the need for permits", "It helps transfer loads and resist movement as designed", "It is used only for decoration", "It eliminates all inspections"],
      answer: "It helps transfer loads and resist movement as designed",
      explanation: "Seismic hardware is part of the structural load path and must be installed as required by plans and code.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with seismic hardware requirements and installation." },
      tags: ["seismic", "hardware", "structure"]
    },
    {
      id: "ca-b-framing-004",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Framing and Structural Components",
      topic: "Decks and stairs",
      difficulty: "medium",
      type: "multiple_choice",
      question: "What is a key concern when laying out stairs?",
      choices: ["Uniform rise and run with code-compliant dimensions", "Using different riser heights for speed", "Choosing paint before measuring", "Skipping attachment details"],
      answer: "Uniform rise and run with code-compliant dimensions",
      explanation: "Stair safety depends on consistent dimensions and proper construction details.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with decks and stairs." },
      tags: ["stairs", "safety", "layout"]
    },
    {
      id: "ca-b-framing-005",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Framing and Structural Components",
      topic: "Siding and stucco",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Before installing exterior siding or stucco, what must be coordinated to protect the building envelope?",
      choices: ["Weather-resistive barriers, flashing, and penetrations", "Furniture delivery", "Final cabinet hardware", "Interior paint sheen"],
      answer: "Weather-resistive barriers, flashing, and penetrations",
      explanation: "Exterior wall assemblies need coordinated moisture protection around openings and penetrations.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with siding and stucco topics." },
      tags: ["siding", "stucco", "weatherproofing"]
    },
    {
      id: "ca-b-core-001",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Core Trades",
      topic: "Plumbing",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Why should plumbing rough-in be coordinated before drywall installation?",
      choices: ["To avoid opening finished walls later", "To choose final paint colors", "To delay inspection", "To reduce the number of plans"],
      answer: "To avoid opening finished walls later",
      explanation: "Core trade rough-ins should be installed and inspected before walls are closed.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Core Trades: plumbing." },
      tags: ["plumbing", "rough-in"]
    },
    {
      id: "ca-b-core-002",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Core Trades",
      topic: "Electrical",
      difficulty: "easy",
      type: "multiple_choice",
      question: "What should a general building contractor coordinate before covering electrical rough work?",
      choices: ["Required inspection and correction of visible issues", "Final carpet cleaning", "Owner move-in date only", "Only the fixture style"],
      answer: "Required inspection and correction of visible issues",
      explanation: "Electrical rough work is a core trade that must be coordinated and inspected before concealment.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Core Trades: electrical." },
      tags: ["electrical", "inspection"]
    },
    {
      id: "ca-b-core-003",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Core Trades",
      topic: "Concrete",
      difficulty: "medium",
      type: "multiple_choice",
      question: "What should be checked before placing concrete for a footing or slab?",
      choices: ["Forms, base preparation, reinforcement, embedded items, and inspection status", "Only the concrete truck color", "Only the landscaping plan", "Only the final flooring material"],
      answer: "Forms, base preparation, reinforcement, embedded items, and inspection status",
      explanation: "Concrete work requires preparation, reinforcement, and inspection coordination before placement.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Core Trades: concrete." },
      tags: ["concrete", "inspection", "reinforcement"]
    },
    {
      id: "ca-b-core-004",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Core Trades",
      topic: "HVAC",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Why should HVAC equipment and duct routes be coordinated early?",
      choices: ["They can affect framing, clearances, penetrations, and other trade work", "They only matter after painting", "They replace the need for insulation", "They are selected after final inspection"],
      answer: "They can affect framing, clearances, penetrations, and other trade work",
      explanation: "HVAC is a core trade that can affect structural coordination, weatherproofing, and finish sequencing.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Core Trades: HVAC." },
      tags: ["hvac", "coordination"]
    },
    {
      id: "ca-b-core-005",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Core Trades",
      topic: "Roofing",
      difficulty: "medium",
      type: "multiple_choice",
      question: "At roof penetrations, which coordination issue is most important?",
      choices: ["Flashing and weatherproofing details", "Interior cabinet style", "Final paint sheen", "Carpet pad thickness"],
      answer: "Flashing and weatherproofing details",
      explanation: "Roofing work must coordinate penetrations and flashing to protect against water intrusion.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Core Trades: roofing." },
      tags: ["roofing", "weatherproofing"]
    },
    {
      id: "ca-b-finish-001",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Finish Trades",
      topic: "Drywall and ceilings",
      difficulty: "easy",
      type: "multiple_choice",
      question: "What should generally be completed before drywall is installed?",
      choices: ["Framing, rough utilities, and required inspections", "Final landscaping", "Cabinet knobs", "Appliance warranty registration"],
      answer: "Framing, rough utilities, and required inspections",
      explanation: "Finish trades follow rough-in and inspection work so concealed items are approved before covering.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Finish Trades: drywall and ceilings." },
      tags: ["drywall", "sequencing"]
    },
    {
      id: "ca-b-finish-002",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Finish Trades",
      topic: "Windows, skylights, and doors",
      difficulty: "medium",
      type: "multiple_choice",
      question: "For exterior windows and doors, what is a major installation concern?",
      choices: ["Flashing and integration with the weather barrier", "Choosing interior furniture", "Skipping shims to save time", "Painting before checking operation"],
      answer: "Flashing and integration with the weather barrier",
      explanation: "Openings must be integrated with moisture-control layers to protect the building envelope.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Finish Trades: windows, skylights, and doors." },
      tags: ["windows", "doors", "flashing"]
    },
    {
      id: "ca-b-finish-003",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Finish Trades",
      topic: "Cabinetry and millwork",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Before installing cabinets, what should be checked?",
      choices: ["Wall layout, backing/support, dimensions, and conflicts with utilities", "Only the brand logo", "Only the final cleaning date", "The roofing inspection card only"],
      answer: "Wall layout, backing/support, dimensions, and conflicts with utilities",
      explanation: "Cabinetry and millwork require coordination with framing, utilities, dimensions, and finish conditions.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Finish Trades: cabinetry and millwork." },
      tags: ["cabinetry", "millwork"]
    },
    {
      id: "ca-b-finish-004",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Finish Trades",
      topic: "Floor covering",
      difficulty: "medium",
      type: "multiple_choice",
      question: "What should be verified before installing floor covering over a substrate?",
      choices: ["Substrate condition, moisture concerns, flatness, and manufacturer requirements", "Only the room name", "Only the wall paint color", "Only the delivery driver's schedule"],
      answer: "Substrate condition, moisture concerns, flatness, and manufacturer requirements",
      explanation: "Finish flooring depends on proper substrate conditions and installation requirements.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Finish Trades: floor covering." },
      tags: ["flooring", "substrate"]
    },
    {
      id: "ca-b-finish-005",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Finish Trades",
      topic: "Painting and coatings",
      difficulty: "easy",
      type: "multiple_choice",
      question: "What is important before applying paint or coating?",
      choices: ["Surface preparation and suitable conditions for the coating system", "Skipping primer whenever possible", "Applying finish before patching", "Using any leftover material regardless of compatibility"],
      answer: "Surface preparation and suitable conditions for the coating system",
      explanation: "Finish quality depends on preparation, compatible materials, and appropriate application conditions.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Finish Trades: painting, staining, and coating." },
      tags: ["painting", "coatings"]
    },
    {
      id: "ca-b-safety-001",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Safety",
      topic: "Personnel safety",
      difficulty: "easy",
      type: "multiple_choice",
      question: "A worker is assigned to a task with a recognized fall hazard. What should be verified before work starts?",
      choices: ["That required fall protection and safety procedures are in place", "That the worker can work faster without protection", "That no one writes down the hazard", "That the task is done only at the end of the day"],
      answer: "That required fall protection and safety procedures are in place",
      explanation: "Safety questions test whether the contractor recognizes hazards and uses appropriate protective measures before work begins.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Safety: personnel safety." },
      tags: ["safety", "fall-protection"]
    },
    {
      id: "ca-b-safety-002",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Safety",
      topic: "Environmental safety",
      difficulty: "medium",
      type: "multiple_choice",
      question: "What should be done when construction activity could allow sediment or debris to leave the site?",
      choices: ["Use appropriate site controls and housekeeping measures", "Wash debris into the street", "Ignore it if the job is short", "Cover it with finish materials"],
      answer: "Use appropriate site controls and housekeeping measures",
      explanation: "Environmental safety includes controlling site conditions that can affect the public, drainage, and surrounding property.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Safety: environmental safety." },
      tags: ["environmental-safety", "site-controls"]
    },
    {
      id: "ca-b-safety-003",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Safety",
      topic: "Transportation and traffic control",
      difficulty: "easy",
      type: "multiple_choice",
      question: "When work affects pedestrian or vehicle movement near a jobsite, what should be planned?",
      choices: ["Traffic and pedestrian control measures appropriate to the hazard", "Only the lunch schedule", "A faster route through the work area", "No signs so the site looks cleaner"],
      answer: "Traffic and pedestrian control measures appropriate to the hazard",
      explanation: "Transportation and traffic control are part of jobsite safety planning.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Safety: transportation and traffic control." },
      tags: ["traffic-control", "safety"]
    },
    {
      id: "ca-b-safety-004",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Safety",
      topic: "Personnel safety",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Why should damaged ladders or unsafe access equipment be removed from service?",
      choices: ["To prevent workers from using equipment that may fail", "To make storage harder", "To avoid buying materials", "To reduce the number of inspections"],
      answer: "To prevent workers from using equipment that may fail",
      explanation: "Personnel safety includes recognizing unsafe equipment and preventing its use.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Safety: personnel safety." },
      tags: ["ladders", "safety"]
    },
    {
      id: "ca-b-safety-005",
      studyGuide: "california-contractors",
      examId: "general-building-b",
      exam: "B - General Building",
      section: "Safety",
      topic: "Personnel safety",
      difficulty: "easy",
      type: "multiple_choice",
      question: "What is the best response when a crew member reports a serious jobsite hazard?",
      choices: ["Correct or control the hazard before continuing affected work", "Tell the crew to ignore it", "Wait until project closeout", "Move the hazard to another trade's area"],
      answer: "Correct or control the hazard before continuing affected work",
      explanation: "Contractors must respond to recognized hazards and keep the jobsite reasonably safe.",
      source: { label: "CSLB B General Building Study Guide", url: "https://www.cslb.ca.gov/resources/studyguides/bstudyguide.pdf", note: "Aligned with Safety: personnel safety." },
      tags: ["hazard", "safety"]
    },
    {
      id: "ca-lb-contracts-001",
      studyGuide: "california-contractors",
      examId: "law-business",
      exam: "Law & Business",
      section: "Contracts and Business Practices",
      topic: "Contract scope",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Why should a contract clearly describe the scope of work?",
      choices: ["To reduce misunderstandings about what is included", "To avoid all written communication", "To hide the price", "To replace required licenses"],
      answer: "To reduce misunderstandings about what is included",
      explanation: "Clear contract scope helps define expectations, pricing, and responsibility for the work.",
      source: { label: "CSLB Examination Study Guides", url: "https://www.cslb.ca.gov/contractors/applicants/Examination_Study_Guides/", note: "Aligned with Law & Business study topics." },
      tags: ["contracts", "scope"]
    },
    {
      id: "ca-lb-compliance-001",
      studyGuide: "california-contractors",
      examId: "law-business",
      exam: "Law & Business",
      section: "Business Compliance",
      topic: "Workers' compensation",
      difficulty: "medium",
      type: "multiple_choice",
      question: "Why is workers' compensation compliance important for a contractor with employees?",
      choices: ["It is part of legal and business responsibility for employee injury coverage", "It replaces jobsite safety", "It applies only after retirement", "It is only a marketing choice"],
      answer: "It is part of legal and business responsibility for employee injury coverage",
      explanation: "Contractors must understand business compliance obligations such as insurance, bonds, and employee-related requirements.",
      source: { label: "CSLB Get Licensed to Build", url: "https://www.cslb.ca.gov/Resources/GuidesAndPublications/GetLicensedToBuild_ENG0525_ADA.pdf", note: "Aligned with licensing and business requirement education." },
      tags: ["workers-compensation", "compliance"]
    },
    {
      id: "ca-licensing-process-001",
      studyGuide: "california-contractors",
      examId: "licensing-process",
      exam: "Licensing Process",
      section: "Application Process",
      topic: "Licensing steps",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Which step is part of becoming licensed through CSLB?",
      choices: ["Submitting an application and meeting exam or waiver requirements", "Only buying tools", "Only creating a business card", "Skipping identity and experience review"],
      answer: "Submitting an application and meeting exam or waiver requirements",
      explanation: "The licensing process includes application review and meeting required qualifications before a license is issued.",
      source: { label: "CSLB Get Licensed to Build", url: "https://www.cslb.ca.gov/Resources/GuidesAndPublications/GetLicensedToBuild_ENG0525_ADA.pdf", note: "Aligned with CSLB licensing process guidance." },
      tags: ["application", "licensing"]
    },
    {
      id: "ca-licensing-process-002",
      studyGuide: "california-contractors",
      examId: "licensing-process",
      exam: "Licensing Process",
      section: "Bonds and Insurance",
      topic: "License maintenance",
      difficulty: "easy",
      type: "multiple_choice",
      question: "Why should a contractor track bond, insurance, and renewal requirements?",
      choices: ["To keep the license in good standing", "To avoid learning the trade", "To replace written contracts", "To skip all CSLB communication"],
      answer: "To keep the license in good standing",
      explanation: "License maintenance includes staying current with ongoing requirements such as bonds, insurance, and renewal obligations.",
      source: { label: "CSLB Get Licensed to Build", url: "https://www.cslb.ca.gov/Resources/GuidesAndPublications/GetLicensedToBuild_ENG0525_ADA.pdf", note: "Aligned with CSLB licensing process guidance." },
      tags: ["bond", "insurance", "renewal"]
    }
  ]
};
